### ISSUE TITLE
python3 compatible

### ISSUE THREAD

**Issue by dgg32** [univieCUBE/PICA#1]
Hello, developer. I wonder, whether is possible to make this program python 3 compatible please. I tried 2to3, but encountered an error by running train.py:

```
File "/mnt/second/Downloads/PICA-master/pica/trainers/libsvm/libSVMTrainer.py", line 8, in <module>
    from libsvm290.python.svm import *
  File "/mnt/second/Downloads/PICA-master/libsvm290/python/svm.py", line 1, in <module>
    from . import svmc
ImportError: /mnt/second/Downloads/PICA-master/libsvm290/python/svmc.so: undefined symbol: _Py_ZeroStruct
```

Thank you!

**Comment by rattei** [comment]
Hello,

thanks for your request. At the moment, we don't plan the migration of the code to python3. The migration would require extensive testing. As PICA runs file on python2 and we therefore don't see any urgent need or direct benefit from a migration.

best regards
Thomas

__________________________________________________________________
                                                                   ue
Prof. Dr. Thomas Rattei                                          bbc
CUBE - Division of Computational Systems Biology                cbc
Dept. of Microbiology and Ecosystem Science         ec       cce.cc
University of Vienna                                 bbbc ccuc....b
Althanstrasse 14                                     c  bb........ce
1090 Vienna, Austria                                     ue........cu
Phone  +43 1 4277 76680                                   ce......c bbue
Mobile +43 664 60277 76680                                 e..ccucc   be
e-mail thomas.rattei@univie.ac.at                           bcc
web    cube.univie.ac.at                                  cbb
________________________________________________________ u c

**Comment by VarIr** [comment]
The new `phenotrex` package is successor to PICA and (among many other improvements) runs on Python 3.7 and higher. Install via `pip install phenotrex` or go to https://github.com/univieCUBE/phenotrex.
